[target.wasm32-unknown-emscripten]
linker = "./util/emcc_wrapper"
rustflags = [
    "-C",
    "panic=abort",
    "-C",
    "link-args=-s MODULARIZE=1 -s ALLOW_MEMORY_GROWTH=1 -s FILESYSTEM=0 -s ENVIRONMENT=web,worker,node -s EXPORT_ES6=1",
]
